# Generated by Django 3.1.2 on 2020-11-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sar_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='regions', to='sar_search.Region'),
        ),
    ]
