# Generated by Django 3.2.10 on 2022-02-10 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lengths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sampler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='fishingarea',
            options={'ordering': ['type', 'name']},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='sampler_ref_number',
            new_name='ref_number',
        ),
        migrations.RemoveField(
            model_name='fishingarea',
            name='herring_area_code',
        ),
        migrations.RemoveField(
            model_name='fishingarea',
            name='nafo_area_code',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='isscfg_code',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='number_of_totes',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='random_tote_number_selected',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='sample_date',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='season',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='vessel_cfvn',
        ),
        migrations.AddField(
            model_name='fishingarea',
            name='name',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fishingarea',
            name='type',
            field=models.IntegerField(choices=[(1, 'herring'), (2, 'groundfish'), (3, 'lobster'), (4, 'NAFO')], default=1, verbose_name='type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gear',
            name='uses_bait',
            field=models.BooleanField(default=False, verbose_name='is bait used with this gear?'),
        ),
        migrations.AddField(
            model_name='sample',
            name='cfvn',
            field=models.IntegerField(blank=True, null=True, verbose_name='commercial fishing vessel number (CFVN)'),
        ),
        migrations.AddField(
            model_name='sample',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lengths_samples_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sample',
            name='bait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='lengths.bait'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='catch_weight_lbs',
            field=models.FloatField(blank=True, null=True, verbose_name='catch weight (lbs)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lengths_samples_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sample',
            name='fishing_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='lengths.fishingarea'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='gear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='lengths.gear'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='mesh_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='lengths.meshsize'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='lengths.port'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_weight_lbs',
            field=models.FloatField(blank=True, null=True, verbose_name='sample weight (lbs)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='lengths.species'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sampler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='lengths.sampler'),
        ),
    ]
